import XCTest
import SwiftData
@testable import TrainingOS

/// Stage 4F: proves `ConcurrentScheduler` places already-materialized
/// Sessions onto a tactical window per the kickoff's explicit contract —
/// hard vs. soft constraints, interference avoidance, double-session
/// pairing, recovery spacing, determinism, and impossible-mix handling
/// via `ScheduleProposal.conflicts` rather than silent dropping. These
/// are placement-algorithm tests: every `Session` here is a bare
/// pre-existing fixture, never generated by a `ProgrammingSystem` —
/// `ConcurrentScheduler` never looks past what it's handed.
@MainActor
final class ConcurrentSchedulerTests: XCTestCase {
    var container: ModelContainer!
    var context: ModelContext!

    override func setUpWithError() throws {
        container = PersistenceController.makeInMemoryContainer()
        context = container.mainContext
    }

    private func freshContext() -> ModelContext {
        ModelContext(container)
    }

    /// 2026-01-05 is a Monday — window offset 0 = Monday, offset 6 = Sunday,
    /// exactly matching `Weekday`'s own Monday-first ordering, so tests can
    /// reason about offsets and weekdays interchangeably.
    private func mondayStart() -> Date {
        Calendar.current.date(from: DateComponents(year: 2026, month: 1, day: 5))!
    }

    private func makeSession(
        _ name: String,
        modality: TrainingModality = .strength,
        stress: TrainingStressProfile? = nil
    ) -> Session {
        let session = Session(name: name, modality: modality)
        context.insert(session)
        if let stress {
            let block = WorkoutBlock(type: .strength, trainingStressProfile: stress)
            context.insert(block)
            session.addBlock(block)
        }
        return session
    }

    private func makeComponent(
        label: String,
        priority: GoalPriority,
        frequency: SessionFrequency,
        flexibility: ComponentFlexibility = .preferred,
        allowsDoubleSessionPairing: Bool = true,
        preferredDays: [Weekday] = [],
        requiredSpacingDays: Int? = nil,
        mix: TrainingMix? = nil
    ) -> TrainingMixComponent {
        let component = TrainingMixComponent(
            label: label,
            priority: priority,
            frequency: frequency,
            flexibility: flexibility,
            allowsDoubleSessionPairing: allowsDoubleSessionPairing,
            preferredDays: preferredDays,
            requiredSpacingDays: requiredSpacingDays
        )
        context.insert(component)
        mix?.addComponent(component)
        return component
    }

    private func heavy(_ modality: ActivityType? = nil) -> TrainingStressProfile {
        TrainingStressProfile(
            overallIntensity: .high, systemicDemand: .high, lowerBodyLoad: .high,
            upperBodyLoad: .low, impactLoading: .high, metabolicDemand: .moderate,
            durationClassification: .medium, modality: modality, recoveryDemand: .high
        )
    }

    private func light(_ modality: ActivityType? = nil) -> TrainingStressProfile {
        TrainingStressProfile(
            overallIntensity: .low, systemicDemand: .low, lowerBodyLoad: .low,
            upperBodyLoad: .none, impactLoading: .low, metabolicDemand: .low,
            durationClassification: .medium, modality: modality, recoveryDemand: .low
        )
    }

    // MARK: - Case B (REQUIRED): symmetric, modality-agnostic placement

    /// The kickoff's explicitly required proof: 3 Strength/Hypertrophy +
    /// 2 Functional Fitness + 1 Running across 6 days. This proves the
    /// scheduler is symmetric — the same `schedule()` call handles all
    /// three systems by construction, with no modality-specific branching
    /// anywhere in `ConcurrentScheduler`.
    func testCaseB_ThreeStrengthTwoFunctionalFitnessOneRunning_AcrossSixDays() throws {
        let mix = TrainingMix(kind: .selected, name: "Case B Hybrid")
        context.insert(mix)

        let strengthComponent = makeComponent(
            label: "Strength", priority: .primary,
            frequency: SessionFrequency(target: 3), mix: mix
        )
        let ffComponent = makeComponent(
            label: "Functional Fitness", priority: .secondary,
            frequency: SessionFrequency(target: 2), mix: mix
        )
        let runningComponent = makeComponent(
            label: "Running", priority: .supporting,
            frequency: SessionFrequency(target: 1), mix: mix
        )

        let strengthSessions = (0..<3).map { makeSession("Strength \($0)", modality: .strength) }
        let ffSessions = (0..<2).map { makeSession("FF \($0)", modality: .functionalFitness) }
        let runningSessions = [makeSession("Long Run", modality: .conditioning)]

        let inputs = [
            ScheduledProgramInput(component: strengthComponent, sessions: strengthSessions),
            ScheduledProgramInput(component: ffComponent, sessions: ffSessions),
            ScheduledProgramInput(component: runningComponent, sessions: runningSessions),
        ]

        let availability = UserAvailability(
            trainingDaysPerWeek: 6,
            unavailableWeekdays: [.sunday],
            allowsDoubleSessions: false,
            maxSessionsPerDay: 1
        )
        let constraints = SchedulingConstraints(
            availability: availability,
            window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 6)
        )

        let proposal = ConcurrentScheduler.schedule(inputs, constraints: constraints)

        XCTAssertEqual(proposal.feasibility, .feasible)
        XCTAssertTrue(proposal.conflicts.isEmpty)
        XCTAssertEqual(proposal.placements.count, 6)

        // Every session got its own day (no doubles possible/needed: 6
        // sessions, 6 usable days).
        let uniqueDates = Set(proposal.placements.map(\.date))
        XCTAssertEqual(uniqueDates.count, 6)
        XCTAssertTrue(proposal.placements.allSatisfy { !$0.isDoubleSessionPairing })

        // Program order preserved within each component.
        let strengthDates = proposal.placements
            .filter { $0.componentLabel == "Strength" }
            .sorted { $0.date < $1.date }
        XCTAssertEqual(strengthDates.map(\.session.name), ["Strength 0", "Strength 1", "Strength 2"])

        // Symmetry: every placement carries `.programOrderPreserved`
        // regardless of which system produced it.
        XCTAssertTrue(proposal.placements.allSatisfy { $0.reasonCodes.contains(.programOrderPreserved) })
        // Primary-tier placements (Strength) are tagged accordingly.
        XCTAssertTrue(proposal.placements.filter { $0.componentLabel == "Strength" }.allSatisfy { $0.reasonCodes.contains(.primaryGoalPriority) })
        // This is the `.selected` mix — every placement should say so.
        XCTAssertTrue(proposal.placements.allSatisfy { $0.reasonCodes.contains(.userSelectedMix) })
    }

    // MARK: - Case A: double-session pairing prefers the lightest partner

    func testCaseA_HypertrophyPrimaryWithAerobicSecondary_DoublesPairWithLightestDays() throws {
        let mix = TrainingMix(kind: .recommended, name: "Case A Muscle Gain")
        context.insert(mix)

        let hypertrophyComponent = makeComponent(
            label: "Hypertrophy", priority: .primary,
            frequency: SessionFrequency(target: 5), mix: mix
        )
        let aerobicComponent = makeComponent(
            label: "Aerobic Base", priority: .secondary,
            frequency: SessionFrequency(target: 2), allowsDoubleSessionPairing: true, mix: mix
        )

        // Five weekday Hypertrophy sessions. The two `.high` days are kept
        // non-adjacent (Wed/Fri) so this fixture isolates double-session
        // pairing behavior without also triggering the primary
        // component's own adjacent-heavy-day interference avoidance —
        // that mechanism is proven separately by the Case C tests.
        let intensities: [LoadLevel] = [.low, .moderate, .high, .moderate, .high]
        let hypertrophySessions = intensities.enumerated().map { index, level in
            makeSession(
                "Hypertrophy \(index)",
                modality: .hypertrophy,
                stress: TrainingStressProfile(
                    overallIntensity: level, systemicDemand: level, lowerBodyLoad: level,
                    upperBodyLoad: level, impactLoading: .none, metabolicDemand: level,
                    durationClassification: .medium, modality: nil, recoveryDemand: level
                )
            )
        }
        let aerobicSessions = (0..<2).map { makeSession("Zone 2 \($0)", modality: .conditioning, stress: light(.running)) }

        let inputs = [
            ScheduledProgramInput(component: hypertrophyComponent, sessions: hypertrophySessions),
            ScheduledProgramInput(component: aerobicComponent, sessions: aerobicSessions),
        ]

        let availability = UserAvailability(
            trainingDaysPerWeek: 5,
            unavailableWeekdays: [.saturday, .sunday],
            allowsDoubleSessions: true,
            maxSessionsPerDay: 2
        )
        let constraints = SchedulingConstraints(
            availability: availability,
            window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7)
        )

        let proposal = ConcurrentScheduler.schedule(inputs, constraints: constraints)

        XCTAssertEqual(proposal.feasibility, .feasible)
        XCTAssertEqual(proposal.placements.count, 7)

        let doubles = proposal.placements.filter { $0.isDoubleSessionPairing }
        XCTAssertEqual(doubles.count, 2)
        XCTAssertTrue(doubles.allSatisfy { $0.componentLabel == "Aerobic Base" })
        XCTAssertTrue(doubles.allSatisfy { $0.reasonCodes.contains(.doubleSessionSelected) })
        XCTAssertTrue(doubles.allSatisfy { $0.reasonCodes.contains(.lowIntensityPairing) })

        // The two doubles must land on the two LIGHTEST Hypertrophy days
        // (index 0 = .low, and one of the two .moderate days) — never on
        // the two .high days, since lighter partners were always
        // available.
        let doubleDates = Set(doubles.map(\.date))
        let hypertrophyByDate = Dictionary(uniqueKeysWithValues: proposal.placements
            .filter { $0.componentLabel == "Hypertrophy" }
            .map { ($0.date, $0.session.name) })
        let pairedHypertrophyNames = Set(doubleDates.compactMap { hypertrophyByDate[$0] })
        XCTAssertEqual(pairedHypertrophyNames, ["Hypertrophy 0", "Hypertrophy 1"])
    }

    // MARK: - Case C: interference avoidance

    func testCaseC_InterferenceAvoidedWhenANonAdjacentDayExists() throws {
        let mix = TrainingMix(kind: .selected, name: "Case C Functional Fitness Primary")
        context.insert(mix)

        let ffComponent = makeComponent(
            label: "Functional Fitness", priority: .primary,
            frequency: SessionFrequency(target: 1), mix: mix
        )
        let strengthComponent = makeComponent(
            label: "Strength", priority: .secondary,
            frequency: SessionFrequency(target: 1), mix: mix
        )

        let ffSession = makeSession("Heavy FF", modality: .functionalFitness, stress: heavy())
        let strengthSession = makeSession("Heavy Squat Day", modality: .strength, stress: heavy())

        let inputs = [
            ScheduledProgramInput(component: ffComponent, sessions: [ffSession]),
            ScheduledProgramInput(component: strengthComponent, sessions: [strengthSession]),
        ]

        // A 3-day window gives the second (lower-priority) session a
        // non-adjacent alternative (offset 2) to the primary's day
        // (offset 0) — the soft interference rule should steer it there.
        let availability = UserAvailability(trainingDaysPerWeek: 3, allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(
            availability: availability,
            window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 3)
        )

        let proposal = ConcurrentScheduler.schedule(inputs, constraints: constraints)

        XCTAssertEqual(proposal.feasibility, .feasible)
        let ffPlacement = try XCTUnwrap(proposal.placements.first { $0.componentLabel == "Functional Fitness" })
        let strengthPlacement = try XCTUnwrap(proposal.placements.first { $0.componentLabel == "Strength" })

        XCTAssertEqual(ffPlacement.date, mondayStart())
        // Non-adjacent to the FF day (offset 0) means offset 2, not offset 1.
        XCTAssertEqual(strengthPlacement.date, Calendar.current.date(byAdding: .day, value: 2, to: mondayStart()))
        XCTAssertTrue(strengthPlacement.reasonCodes.contains(.interferenceAvoided))
        XCTAssertFalse(strengthPlacement.reasonCodes.contains(.softConstraintViolated))
    }

    func testCaseC_InterferenceViolatedWhenNoAlternativeDayExists() throws {
        let mix = TrainingMix(kind: .selected, name: "Forced Adjacency")
        context.insert(mix)

        let ffComponent = makeComponent(label: "Functional Fitness", priority: .primary, frequency: SessionFrequency(target: 1), mix: mix)
        let strengthComponent = makeComponent(label: "Strength", priority: .secondary, frequency: SessionFrequency(target: 1), mix: mix)

        let ffSession = makeSession("Heavy FF", modality: .functionalFitness, stress: heavy())
        let strengthSession = makeSession("Heavy Squat Day", modality: .strength, stress: heavy())

        let inputs = [
            ScheduledProgramInput(component: ffComponent, sessions: [ffSession]),
            ScheduledProgramInput(component: strengthComponent, sessions: [strengthSession]),
        ]

        // Only a 2-day window — no non-adjacent day is possible at all.
        let availability = UserAvailability(trainingDaysPerWeek: 2, allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(
            availability: availability,
            window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 2)
        )

        let proposal = ConcurrentScheduler.schedule(inputs, constraints: constraints)

        XCTAssertEqual(proposal.feasibility, .feasibleWithSoftViolations)
        XCTAssertTrue(proposal.conflicts.isEmpty, "the session was still placed — a soft violation, not a dropped session")
        let strengthPlacement = try XCTUnwrap(proposal.placements.first { $0.componentLabel == "Strength" })
        XCTAssertTrue(strengthPlacement.reasonCodes.contains(.softConstraintViolated))
        XCTAssertFalse(proposal.warnings.isEmpty)
    }

    // MARK: - Hard constraints

    func testUnavailableWeekdayIsNeverUsed() throws {
        let mix = TrainingMix(kind: .selected, name: "Mix")
        context.insert(mix)
        let component = makeComponent(label: "Strength", priority: .primary, frequency: SessionFrequency(target: 3), mix: mix)
        let sessions = (0..<3).map { makeSession("S\($0)") }

        let availability = UserAvailability(trainingDaysPerWeek: 7, unavailableWeekdays: [.tuesday, .thursday], allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7))

        let proposal = ConcurrentScheduler.schedule([ScheduledProgramInput(component: component, sessions: sessions)], constraints: constraints)

        let weekdaysUsed = Set(proposal.placements.map { Calendar.current.component(.weekday, from: $0.date) })
        // Tuesday = weekday 3, Thursday = weekday 5 in Calendar's own convention.
        XCTAssertFalse(weekdaysUsed.contains(3))
        XCTAssertFalse(weekdaysUsed.contains(5))
    }

    func testMaxSessionsPerDayIsNeverExceededEvenWithDoublesAllowed() throws {
        let mix = TrainingMix(kind: .selected, name: "Mix")
        context.insert(mix)
        let a = makeComponent(label: "A", priority: .primary, frequency: SessionFrequency(target: 1), mix: mix)
        let b = makeComponent(label: "B", priority: .secondary, frequency: SessionFrequency(target: 1), mix: mix)
        let c = makeComponent(label: "C", priority: .supporting, frequency: SessionFrequency(target: 1), mix: mix)

        let sessionA = makeSession("A0")
        let sessionB = makeSession("B0")
        let sessionC = makeSession("C0")

        // Only ONE usable day, but max 2 sessions/day — the third must
        // become a conflict, never a silent third occupant.
        let availability = UserAvailability(trainingDaysPerWeek: 1, availableWeekdays: [.monday], allowsDoubleSessions: true, maxSessionsPerDay: 2)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 1))

        let proposal = ConcurrentScheduler.schedule([
            ScheduledProgramInput(component: a, sessions: [sessionA]),
            ScheduledProgramInput(component: b, sessions: [sessionB]),
            ScheduledProgramInput(component: c, sessions: [sessionC]),
        ], constraints: constraints)

        XCTAssertEqual(proposal.placements.count, 2)
        XCTAssertEqual(proposal.feasibility, .infeasible)
        XCTAssertEqual(proposal.conflicts.count, 1)
        XCTAssertEqual(proposal.conflicts.first?.componentLabel, "C")
    }

    func testRequiredSpacingDaysIsEnforcedAsAHardConstraint() throws {
        let mix = TrainingMix(kind: .selected, name: "Mix")
        context.insert(mix)
        let component = makeComponent(
            label: "Intervals", priority: .primary,
            frequency: SessionFrequency(target: 2), requiredSpacingDays: 3, mix: mix
        )
        let sessions = (0..<2).map { makeSession("Interval \($0)") }

        let availability = UserAvailability(trainingDaysPerWeek: 7, allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7))

        let proposal = ConcurrentScheduler.schedule([ScheduledProgramInput(component: component, sessions: sessions)], constraints: constraints)

        XCTAssertEqual(proposal.placements.count, 2)
        let dates = proposal.placements.sorted { $0.date < $1.date }.map(\.date)
        let gap = Calendar.current.dateComponents([.day], from: dates[0], to: dates[1]).day ?? 0
        XCTAssertGreaterThanOrEqual(gap, 3)
        XCTAssertTrue(proposal.placements.last { $0.date == dates[1] }?.reasonCodes.contains(.recoverySpacing) ?? false)
    }

    // MARK: - Preferred days

    func testPreferredDayIsUsedWhenAvailableAndFlaggedOtherwise() throws {
        let mix = TrainingMix(kind: .selected, name: "Mix")
        context.insert(mix)
        let component = makeComponent(
            label: "Strength", priority: .primary,
            frequency: SessionFrequency(target: 1), preferredDays: [.wednesday], mix: mix
        )
        let session = makeSession("S0")

        let availability = UserAvailability(trainingDaysPerWeek: 7, allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7))

        let proposal = ConcurrentScheduler.schedule([ScheduledProgramInput(component: component, sessions: [session])], constraints: constraints)

        let placement = try XCTUnwrap(proposal.placements.first)
        XCTAssertEqual(placement.date, Calendar.current.date(byAdding: .day, value: 2, to: mondayStart()))
        XCTAssertTrue(placement.reasonCodes.contains(.preferredDayUsed))
    }

    func testSoftConstraintViolatedWhenNoPreferredDayIsAvailableAtAll() throws {
        let mix = TrainingMix(kind: .selected, name: "Mix")
        context.insert(mix)
        let component = makeComponent(
            label: "Strength", priority: .primary,
            frequency: SessionFrequency(target: 1), preferredDays: [.wednesday], mix: mix
        )
        let session = makeSession("S0")

        let availability = UserAvailability(trainingDaysPerWeek: 6, unavailableWeekdays: [.wednesday], allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7))

        let proposal = ConcurrentScheduler.schedule([ScheduledProgramInput(component: component, sessions: [session])], constraints: constraints)

        let placement = try XCTUnwrap(proposal.placements.first)
        XCTAssertFalse(placement.reasonCodes.contains(.preferredDayUsed))
        XCTAssertTrue(placement.reasonCodes.contains(.softConstraintViolated))
        XCTAssertEqual(proposal.feasibility, .feasibleWithSoftViolations)
        XCTAssertFalse(proposal.warnings.isEmpty)
    }

    // MARK: - User-selected vs recommended

    func testUserSelectedMixReasonCodeOnlyAppliesToTheSelectedMix() throws {
        let selectedMix = TrainingMix(kind: .selected, name: "Selected")
        context.insert(selectedMix)
        let recommendedMix = TrainingMix(kind: .recommended, name: "Recommended")
        context.insert(recommendedMix)

        let selectedComponent = makeComponent(label: "Selected Strength", priority: .primary, frequency: SessionFrequency(target: 1), mix: selectedMix)
        let recommendedComponent = makeComponent(label: "Recommended Strength", priority: .primary, frequency: SessionFrequency(target: 1), mix: recommendedMix)

        let availability = UserAvailability(trainingDaysPerWeek: 7, allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 2))

        let selectedProposal = ConcurrentScheduler.schedule(
            [ScheduledProgramInput(component: selectedComponent, sessions: [makeSession("S")])],
            constraints: constraints
        )
        let recommendedProposal = ConcurrentScheduler.schedule(
            [ScheduledProgramInput(component: recommendedComponent, sessions: [makeSession("R")])],
            constraints: constraints
        )

        XCTAssertTrue(selectedProposal.placements.allSatisfy { $0.reasonCodes.contains(.userSelectedMix) })
        XCTAssertTrue(recommendedProposal.placements.allSatisfy { !$0.reasonCodes.contains(.userSelectedMix) })
    }

    // MARK: - Determinism

    func testIdenticallyShapedInputsAlwaysProduceTheSameSchedule() throws {
        func buildInputs() -> [ScheduledProgramInput] {
            let mix = TrainingMix(kind: .selected, name: "Mix")
            context.insert(mix)
            let strength = makeComponent(label: "Strength", priority: .primary, frequency: SessionFrequency(target: 3), mix: mix)
            let ff = makeComponent(label: "Functional Fitness", priority: .secondary, frequency: SessionFrequency(target: 2), mix: mix)
            let running = makeComponent(label: "Running", priority: .supporting, frequency: SessionFrequency(target: 1), mix: mix)
            return [
                ScheduledProgramInput(component: strength, sessions: (0..<3).map { makeSession("Strength \($0)") }),
                ScheduledProgramInput(component: ff, sessions: (0..<2).map { makeSession("FF \($0)", stress: heavy()) }),
                ScheduledProgramInput(component: running, sessions: [makeSession("Run", stress: light(.running))]),
            ]
        }

        let availability = UserAvailability(trainingDaysPerWeek: 6, unavailableWeekdays: [.sunday], allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 6))

        let firstProposal = ConcurrentScheduler.schedule(buildInputs(), constraints: constraints)
        let secondProposal = ConcurrentScheduler.schedule(buildInputs(), constraints: constraints)

        func signature(_ proposal: ScheduleProposal) -> [String] {
            proposal.placements
                .sorted { $0.componentLabel == $1.componentLabel ? $0.date < $1.date : $0.componentLabel < $1.componentLabel }
                .map { placement -> String in
                    let dayOffset = placement.date.timeIntervalSince1970 - proposal.window.startDate.timeIntervalSince1970
                    let sortedReasonCodes = placement.reasonCodes.sorted { $0.rawValue < $1.rawValue }
                    return "\(placement.componentLabel)|\(dayOffset)|\(sortedReasonCodes)"
                }
        }

        XCTAssertEqual(signature(firstProposal), signature(secondProposal))
        XCTAssertEqual(firstProposal.feasibility, secondProposal.feasibility)
    }

    // MARK: - Impossible mix handling

    func testInfeasibleMixNeverSilentlyDropsSessionsAndOffersResolutionOptions() throws {
        let mix = TrainingMix(kind: .selected, name: "Impossible Mix")
        context.insert(mix)
        let component = makeComponent(
            label: "Overloaded", priority: .primary,
            frequency: SessionFrequency(target: 5, minimum: 5),
            flexibility: .required,
            allowsDoubleSessionPairing: false,
            mix: mix
        )
        let sessions = (0..<5).map { makeSession("S\($0)") }

        // Only 2 usable days, doubles disallowed for this required
        // component — 5 sessions cannot possibly fit.
        let availability = UserAvailability(trainingDaysPerWeek: 2, availableWeekdays: [.monday, .tuesday], allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7))

        let proposal = ConcurrentScheduler.schedule([ScheduledProgramInput(component: component, sessions: sessions)], constraints: constraints)

        XCTAssertEqual(proposal.feasibility, .infeasible)
        XCTAssertEqual(proposal.placements.count, 2, "the 2 that DID fit must still be placed, not discarded")
        let conflict = try XCTUnwrap(proposal.conflicts.first)
        XCTAssertEqual(conflict.unplacedSessions.count, 3)
        // `.required` flexibility must never offer to shrink itself.
        XCTAssertFalse(conflict.resolutionOptions.contains { if case .reduceFrequency = $0 { return true }; return false })
        XCTAssertFalse(conflict.resolutionOptions.contains { if case .shortenOrMoveFlexibleSession = $0 { return true }; return false })
        // Allowing doubles or adding an available day are still valid,
        // real fixes — must be offered.
        XCTAssertTrue(conflict.resolutionOptions.contains { if case .allowDoubleSessions = $0 { return true }; return false })
        XCTAssertTrue(conflict.resolutionOptions.contains { if case .addAvailableDay = $0 { return true }; return false })
    }

    // MARK: - GoalAlignmentEvaluator

    func testGoalAlignmentIsExcellentWhenEverythingIsSatisfied() throws {
        let mix = TrainingMix(kind: .selected, name: "Mix")
        context.insert(mix)
        let component = makeComponent(label: "Strength", priority: .primary, frequency: SessionFrequency(target: 3), mix: mix)
        let sessions = (0..<3).map { makeSession("S\($0)") }

        let availability = UserAvailability(trainingDaysPerWeek: 7, allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7))
        let proposal = ConcurrentScheduler.schedule([ScheduledProgramInput(component: component, sessions: sessions)], constraints: constraints)

        let alignment = GoalAlignmentEvaluator.evaluate(mix: mix, proposal: proposal)
        XCTAssertEqual(alignment.rating, .excellent)
        XCTAssertTrue(alignment.factors.allSatisfy(\.satisfied))
    }

    func testGoalAlignmentIsPoorWhenInfeasible() throws {
        let mix = TrainingMix(kind: .selected, name: "Mix")
        context.insert(mix)
        let component = makeComponent(
            label: "Overloaded", priority: .primary,
            frequency: SessionFrequency(target: 5, minimum: 5), flexibility: .required,
            allowsDoubleSessionPairing: false, mix: mix
        )
        let sessions = (0..<5).map { makeSession("S\($0)") }

        let availability = UserAvailability(trainingDaysPerWeek: 2, availableWeekdays: [.monday, .tuesday], allowsDoubleSessions: false, maxSessionsPerDay: 1)
        let constraints = SchedulingConstraints(availability: availability, window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7))
        let proposal = ConcurrentScheduler.schedule([ScheduledProgramInput(component: component, sessions: sessions)], constraints: constraints)

        let alignment = GoalAlignmentEvaluator.evaluate(mix: mix, proposal: proposal)
        XCTAssertEqual(alignment.rating, .poor)
        let feasibilityFactor = try XCTUnwrap(alignment.factors.first { $0.kind == .schedulingFeasibility })
        XCTAssertFalse(feasibilityFactor.satisfied)
    }

    // MARK: - AcceptScheduleProposalUseCase persistence

    func testAcceptingAProposalReparentsSessionsAndStampsSchedulerVersion() throws {
        let ownerUserID = UUID()
        let naiveDay = Day(ownerUserID: ownerUserID, date: mondayStart())
        context.insert(naiveDay)
        let session = makeSession("S0")
        naiveDay.addSession(session)
        try context.save()

        let mix = TrainingMix(kind: .selected, name: "Mix")
        context.insert(mix)
        let component = makeComponent(label: "Strength", priority: .primary, frequency: SessionFrequency(target: 1), mix: mix)

        let targetDate = Calendar.current.date(byAdding: .day, value: 5, to: mondayStart())!
        let proposal = ScheduleProposal(
            schedulerVersion: ConcurrentScheduler.currentVersion,
            window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7),
            placements: [SessionPlacement(session: session, componentLabel: component.label, date: targetDate, sortIndexInDay: 0, reasonCodes: [.programOrderPreserved])],
            conflicts: [],
            feasibility: .feasible
        )

        try AcceptScheduleProposalUseCase.accept(proposal, ownerUserID: ownerUserID, context: context)
        try context.save()

        XCTAssertTrue(naiveDay.sessions.isEmpty, "the naive Day must no longer hold the re-placed Session")
        XCTAssertEqual(session.day?.date, targetDate)
        XCTAssertEqual(session.schedulerVersion, ConcurrentScheduler.currentVersion)
        XCTAssertEqual(session.scheduledTime, targetDate)

        let sessionID = session.id
        let reloaded = try XCTUnwrap(freshContext().fetch(FetchDescriptor<Session>(predicate: #Predicate { $0.id == sessionID })).first)
        XCTAssertEqual(reloaded.schedulerVersion, ConcurrentScheduler.currentVersion)
        XCTAssertEqual(reloaded.day?.date, targetDate)
    }

    func testAcceptingAnInfeasibleProposalThrowsAndMutatesNothing() throws {
        let ownerUserID = UUID()
        let session = makeSession("S0")
        let naiveDay = Day(ownerUserID: ownerUserID, date: mondayStart())
        context.insert(naiveDay)
        naiveDay.addSession(session)
        try context.save()

        let proposal = ScheduleProposal(
            schedulerVersion: ConcurrentScheduler.currentVersion,
            window: SchedulingWindow(startDate: mondayStart(), numberOfDays: 7),
            placements: [],
            conflicts: [SchedulingConflict(componentLabel: "X", unplacedSessions: [], reason: "no room", resolutionOptions: [])],
            feasibility: .infeasible
        )

        XCTAssertThrowsError(try AcceptScheduleProposalUseCase.accept(proposal, ownerUserID: ownerUserID, context: context)) { error in
            XCTAssertEqual(error as? ScheduleAcceptanceError, .infeasible)
        }
        XCTAssertEqual(naiveDay.sessions.count, 1, "an infeasible proposal must never mutate the calendar")
        XCTAssertNil(session.schedulerVersion)
    }
}
