import Foundation

/// FUNCTIONAL FITNESS PROGRAMMING AUTHORITY V2, Section 8: which
/// programming purpose is requesting this movement — the two states this
/// checkpoint has real authority over. `.conditioning` is the only
/// purpose any real dynamically-composed FF block serves today (no
/// allocator yet assigns a genuine SKILL/PRACTICE block — Section 9's
/// own text: "skill work requires a real programming assignment," which
/// this checkpoint does not build); `.skillPractice` exists so the exact
/// gating rule is ready the moment that assignment mechanism is built,
/// without another gating rewrite.
enum MovementSelectionPurpose {
    case conditioning
    case skillPractice
}

/// PROGRAMMING AUTHORITY V1 Part XIV: movement-role-before-exercise
/// selection, formalized as its own named type. `FunctionalFitnessMovementComposer`
/// already selects the MovementFunction (the "role") before this type ever
/// runs — programming already requests a role before a concrete exercise,
/// structurally, at the one real dynamically-composed FF call site. This
/// type owns only the second half of that pipeline: given an
/// already-decided role (`ExerciseSlot`/`MovementFunction`), which concrete
/// `Exercise` fills it.
///
/// Extracted from `FunctionalFitnessMaterializer.materializeDynamicBlock`'s
/// previously-inline loop body with NO logic change — every existing
/// fixture/test exercises this exact code path and resolves to the
/// identical `Exercise` it did before extraction (proven by the full suite
/// staying green with zero fixture-output changes after this refactor).
///
/// Implements the priority order from the original specification's
/// exercise-selection list:
///   1. programming-role fit
///   2. athlete capability
///   3. environment/equipment
///   4. source obligation where applicable
///   5. whole-week exposure
///   6. local fatigue
///   7. same-session complementarity
///   8. progression continuity
///   9. deterministic tie-breaking
///
/// with two honest scoping notes, not silent decisions:
///
/// - **Step 4 (source obligation) does not apply at this call site.** Only
///   `isDynamicallyComposed == true` FF templates ever reach this
///   selector; source-backed programs (Hypertrophy/Strength/Powerlifting/
///   Running) are generated by entirely separate generators this type
///   never touches, so there is no source obligation for this selector to
///   honor or violate.
/// - **Step 6 (local fatigue) has no separate tracked signal.** This
///   codebase's real fatigue proxy for exercise selection is exposure
///   count (steps 5/9 below) — a genuinely distinct local-fatigue model
///   (e.g. per-muscle-group recent tonnage) does not exist and is not
///   fabricated here; `ProgrammingValidator.validateStressClustering`
///   handles fatigue at the coarser whole-week `Stimulus.systemicDemand`
///   level, a different axis than per-exercise selection.
///
/// One pre-existing, already-approved deliberate exception to the generic
/// step order is preserved exactly, not newly introduced: **step 8
/// (progression continuity) is checked before step 2 (athlete capability)
/// applies to it** — a real GOING FORWARD athlete preference always wins
/// outright, including over the automatic capability guard rail (Dogfood
/// Round 1 — Final Close, Finding 3C). An athlete's own explicit, already-
/// recorded choice is informed consent this codebase has never treated as
/// subordinate to a guard rail meant for the SYSTEM's own uninformed
/// automatic pick. Steps 1/3/7 still gate a GOING FORWARD preference
/// exactly as before — it only wins when it remains a member of
/// `eligible`.
enum MovementRoleExerciseSelector {
    struct Input {
        let function: MovementFunction
        let slot: ExerciseSlot
        let candidateExercises: [Exercise]
        let environment: TrainingEnvironment
        /// DOGFOOD — FIX ORDER 1, Section C: needed to check
        /// `FunctionalFitnessMovementTargetRule.hasExecutableTarget` per
        /// candidate — a candidate this rule cannot truthfully dose
        /// (e.g. Assault Bike for a monostructural role) must never be
        /// selected when any other real, dosable candidate is eligible.
        let modality: FunctionalModality
        /// Same-function-in-this-session exclusivity: a multi-function
        /// Exercise (e.g. Wall Ball/Thruster/Dumbbell Snatch) may fill
        /// only ONE role per session.
        let usedExerciseIDsThisSession: Set<UUID>
        /// Step 7: the same session's own already-resolved main-body
        /// exercises — a soft preference, never a hard exclusion.
        let sameSessionMainBodyExerciseIDs: Set<UUID>
        /// FUNCTIONAL FITNESS V2 RESISTANCE AUTHORITY COMPLETION, Section
        /// 16-18: which `MovementFunction` patterns already received
        /// MEANINGFUL resistance exposure earlier in this SAME session
        /// (e.g. Back Squat's `.squatLoaded`), regardless of exact
        /// Exercise ID — generalizes `sameSessionMainBodyExerciseIDs`
        /// (exact-ID reuse only) to pattern-level reuse, so a later
        /// Goblet Squat is recognized as sharing `.squatLoaded` with an
        /// earlier Back Squat rather than being treated as unrelated
        /// merely because it's a different `Exercise`. Additive, defaults
        /// empty — every pre-existing call site/test that doesn't pass it
        /// is completely unaffected. A soft preference only (Section 18:
        /// "prefer... but do NOT prohibit repeated patterns when the
        /// assignment requires them") — falls back to an exposed-pattern
        /// candidate when no unexposed alternative exists, exactly like
        /// the pre-existing exact-ID variety preference already does.
        var sameSessionMainBodyExposedPatterns: Set<MovementFunction> = []
        /// Step 8: the athlete's own real, already-recorded GOING FORWARD
        /// choice for this exact role, if any.
        let preferredExercise: Exercise?
        /// Step 5: this SAME component's own already-resolved picks for
        /// this role, earlier in the SAME week.
        let thisWeekExposureForFunction: [UUID: Int]
        /// Step 5 secondary horizon: the immediately preceding tactical
        /// week's real exposure for this role — used only to break a
        /// this-week tie, never merged with it.
        let priorWeekExposureForFunction: [UUID: Int]
        /// FUNCTIONAL FITNESS PROGRAMMING AUTHORITY V2, Section 8: which
        /// purpose this selection serves. Defaults `.conditioning` —
        /// every real call site today.
        var purpose: MovementSelectionPurpose = .conditioning
        /// MUSCLE + 5FF FINAL CLOSURE, Section 9: the real, resolved
        /// `Stimulus.targetDurationDomain` this role is being composed
        /// for — needed so `FunctionalFitnessMovementTargetRule
        /// .hasExecutableTarget` can tell a genuine SUSTAINED_AEROBIC
        /// (`.long`) monostructural role apart from a SHORT_HIGH_OUTPUT
        /// one. Defaults `.short` — every pre-existing call site keeps
        /// the exact prior fixed-200m-distance behavior byte-for-byte,
        /// since only `.long` changes anything (see that rule's own doc
        /// comment).
        var targetDurationDomain: DurationDomain = .short
        /// Section 5/8: the athlete's real, per-exercise proficiency.
        /// `nil` (every pre-existing call site) preserves the exact
        /// prior behavior byte-for-byte — capability gating remains the
        /// GLOBAL `Exercise.requiresDemonstratedCapability` flag alone,
        /// with no per-athlete override, exactly as before this
        /// checkpoint. A non-nil closure activates the real Section 8
        /// purpose-specific gating below.
        var proficiency: ((Exercise) -> MovementProficiency)? = nil
        /// CONDITIONING DOSE AUTHORITY V1, Sections 10-13: the athlete's
        /// real, per-exercise capacity evidence, when recorded. `nil`
        /// (every pre-existing call site) preserves prior behavior
        /// byte-for-byte. Only consulted for the 7 real gated movements
        /// where `TechnicalCapacityDoseAuthority.repeatedDoseTrackedNames`
        /// says max-unbroken-reps/max-reps is a truthful repeated dose.
        var capacity: ((Exercise) -> (type: MovementCapacityType, value: Double)?)? = nil
        /// CONDITIONING V2 — LIVE RUNNING CONTRIBUTION + MODALITY
        /// SELECTION, Sections 8-11: whether the SAME tactical week
        /// already carries real source Running impact (derived from
        /// `RunningWeeklyContribution.hasRunningImpact` for this exact
        /// week — never a whole-program aggregate). `false` (every
        /// pre-existing call site) preserves prior behavior byte-for-byte.
        var weeklyRunningImpact: Bool = false
        /// MUSCLE VERTICAL SLICE REPAIR, Section 14: the real, already-
        /// resolved stimulus intensity this exact role is being composed
        /// for. `nil` (every pre-existing call site) preserves prior
        /// behavior byte-for-byte. When set, a candidate whose own
        /// `Exercise.intendedIntensity` is a dedicated, STRICTLY LOWER
        /// classification (e.g. a real `.low`-tagged variant selected for
        /// a `.high`-intensity role) is excluded — never inferred from
        /// the exercise's display name. An unclassified candidate
        /// (`intendedIntensity == nil`, the overwhelming majority of the
        /// real catalog) is always eligible regardless of this value.
        var requiredIntensity: IntensityClassification? = nil
    }

    enum Resolution: Equatable {
        case resolved(Exercise)
        case none
        /// Step 2: every remaining eligible candidate requires
        /// demonstrated capability this app has no real confirmation of —
        /// the caller must fail honestly (typed), never auto-prescribe.
        case capabilityUnknown(Exercise)
        /// DOGFOOD — FIX ORDER 1, Section C: real, role/environment-
        /// eligible candidates exist, but NONE of them can receive a
        /// truthful, executable target from `FunctionalFitnessMovementTargetRule`
        /// (e.g. every remaining candidate is bike-equipment monostructural
        /// work with no authored quantity) — distinct from `.none`, which
        /// means no role/environment-eligible candidate existed at all.
        /// The caller must fail honestly rather than persist an
        /// unexecutable movement.
        case noExecutableTarget

        static func == (lhs: Resolution, rhs: Resolution) -> Bool {
            switch (lhs, rhs) {
            case (.none, .none): return true
            case (.noExecutableTarget, .noExecutableTarget): return true
            case let (.resolved(a), .resolved(b)): return a.id == b.id
            case let (.capabilityUnknown(a), .capabilityUnknown(b)): return a.id == b.id
            default: return false
            }
        }
    }

    static func select(_ input: Input) -> Resolution {
        // Steps 1 + 3 (programming-role fit, environment/equipment):
        // `SubstitutionValidator.isValid` checks both together against
        // this slot's own `allowedMovementFunctions`/`allowedModalities`
        // and TE.1 compatibility — plus same-session exclusivity for a
        // multi-function exercise.
        let semanticEligible = input.candidateExercises.filter {
            SubstitutionValidator.isValid(candidate: $0, for: input.slot, environment: input.environment)
                && !input.usedExerciseIDsThisSession.contains($0.id)
        }

        // DOGFOOD — FIX ORDER 1, Section C: exclude any candidate this
        // rule cannot truthfully dose (e.g. Assault Bike for a
        // monostructural role) BEFORE ranking by variety/exposure — a
        // candidate with no executable target must never win selection
        // merely because it happens to be least-exposed. Distinguished
        // from `semanticEligible` being empty (that remains `.none`,
        // unchanged) so the caller can tell "no role/environment fit"
        // apart from "fit exists but nothing here can be truthfully
        // prescribed."
        let executableEligible = semanticEligible.filter {
            FunctionalFitnessMovementTargetRule.hasExecutableTarget(
                modality: input.modality, movementFunctions: [input.function], exercise: $0,
                targetDurationDomain: input.targetDurationDomain
            )
        }
        if !semanticEligible.isEmpty, executableEligible.isEmpty {
            return .noExecutableTarget
        }

        // MUSCLE VERTICAL SLICE REPAIR, Section 14: a HARD exclusion
        // (unlike the soft impact/variety preferences below) — a
        // dedicated LOW-intensity exercise variant cannot truthfully
        // serve a role that requires a strictly higher intensity, no
        // matter how exposed/unexposed it is. Only fires when both this
        // role's required intensity AND the candidate's own declared
        // intensity are known (the overwhelming majority of exercises
        // are `nil`/unclassified and are therefore never touched by this
        // check). If excluding intensity-incompatible candidates would
        // leave nothing where real candidates existed, that is exactly
        // the same "eligible existed but none can truthfully serve this
        // role" situation `.noExecutableTarget` already exists to name.
        func isIntensityCompatible(_ exercise: Exercise) -> Bool {
            guard let required = input.requiredIntensity, let declared = exercise.intendedIntensity else { return true }
            let order: [IntensityClassification] = [.low, .moderate, .high]
            guard let requiredIndex = order.firstIndex(of: required), let declaredIndex = order.firstIndex(of: declared) else { return true }
            return declaredIndex >= requiredIndex
        }
        let intensityEligible = executableEligible.filter(isIntensityCompatible)
        if !executableEligible.isEmpty, intensityEligible.isEmpty {
            return .noExecutableTarget
        }
        let executableEligible2 = intensityEligible.isEmpty ? executableEligible : intensityEligible

        // Step 7 (same-session complementarity): prefer a candidate not
        // already used by this session's own main body — but only when a
        // genuine alternative exists; steps 1/3 above always win over
        // variety (capability/environment constraints beat complementarity).
        // Section 16-18: pattern-level reuse (a candidate sharing a
        // MovementFunction with earlier MEANINGFUL same-session exposure,
        // e.g. Goblet Squat after Back Squat) is treated the same soft
        // way as exact-ID reuse — not a ban, just a preference for a
        // genuinely complementary alternative when one exists.
        let varietyPreferred = executableEligible2.filter {
            !input.sameSessionMainBodyExerciseIDs.contains($0.id)
                && Set($0.movementFunctions).isDisjoint(with: input.sameSessionMainBodyExposedPatterns)
        }
        let variedEligible = varietyPreferred.isEmpty ? executableEligible2 : varietyPreferred

        // CONDITIONING V2 — LIVE RUNNING CONTRIBUTION + MODALITY
        // SELECTION, Sections 8-11: step 7 (weekly fatigue/impact) —
        // when this week already carries real source Running impact,
        // prefer a lower-impact cyclical alternative (Assault Bike/Row
        // Erg/SkiErg — any monostructural candidate that genuinely
        // requires cyclical equipment) over a running-pattern candidate
        // (Easy Run/Track Interval Run — real, equipment-free
        // locomotion), but ONLY when a lower-impact alternative already
        // exists among the real eligible candidates here — never
        // invented, never fabricated availability (Section 9's own
        // "do NOT hard-code availability"). A preference, not a ban
        // (Section 10): when no lower-impact alternative is eligible
        // (e.g. no bike/rower/skiErg in this athlete's real environment),
        // running remains fully selectable — the filter falls back to
        // the unfiltered set exactly like the pre-existing variety/
        // pattern preferences above.
        func isHigherImpactRunningPattern(_ exercise: Exercise) -> Bool {
            exercise.movementFunctions.contains(.monostructural) && exercise.requiredEquipment.isEmpty
        }
        let impactPreferred: [Exercise]
        if input.weeklyRunningImpact,
           variedEligible.contains(where: { isHigherImpactRunningPattern($0) }),
           variedEligible.contains(where: { $0.movementFunctions.contains(.monostructural) && !isHigherImpactRunningPattern($0) }) {
            impactPreferred = variedEligible.filter { !isHigherImpactRunningPattern($0) }
        } else {
            impactPreferred = variedEligible
        }
        let eligible = impactPreferred

        // Step 9 (deterministic tie-breaking), applied as the comparator
        // for step 5 (whole-week exposure, then prior-week exposure):
        // least-this-week-exposed first, tie-broken by least-prior-week-
        // exposed, tie-broken by stable canonicalName ordering — never
        // catalog order, never random.
        let leastExposedFirst: (Exercise, Exercise) -> Bool = { a, b in
            let thisWeekA = input.thisWeekExposureForFunction[a.id] ?? 0
            let thisWeekB = input.thisWeekExposureForFunction[b.id] ?? 0
            if thisWeekA != thisWeekB { return thisWeekA < thisWeekB }
            let priorA = input.priorWeekExposureForFunction[a.id] ?? 0
            let priorB = input.priorWeekExposureForFunction[b.id] ?? 0
            if priorA != priorB { return priorA < priorB }
            return a.canonicalName < b.canonicalName
        }

        // Step 8 (progression continuity), deliberately before step 2 —
        // see this type's own doc comment for why (Finding 3C).
        if let preferredExercise = input.preferredExercise, let overridden = eligible.first(where: { $0.id == preferredExercise.id }) {
            return .resolved(overridden)
        }

        // Step 2 (athlete capability): the automatic (non-preference) pick
        // must never land on an exercise this app has no real per-athlete
        // capability confirmation for, while a real ordinary alternative
        // remains eligible.
        //
        // FUNCTIONAL FITNESS PROGRAMMING AUTHORITY V2, Section 8: when a
        // real per-athlete `proficiency` lookup is supplied, a gated
        // exercise's eligibility is now purpose-specific (CONDITIONING
        // requires `.workoutReady`; SKILL/PRACTICE accepts `.learning` or
        // `.workoutReady`) rather than the flat "never automatic" rule.
        // `.unknown` is never eligible for either purpose (Section 8:
        // "UNKNOWN may only enter a skill-assessment/onboarding path, not
        // silently become high-intensity work"). When no lookup is
        // supplied, falls back to the exact pre-existing rule (the global
        // flag alone excludes it) — zero behavior change for any call
        // site that hasn't wired in per-athlete capability yet.
        func isCapabilityEligible(_ exercise: Exercise) -> Bool {
            // CONDITIONING V2 FINAL COMPLETION PASS, Section 1-2: these 5
            // gated movements have no truthful automatic Conditioning
            // dosage authority at all (not a rep-based dosing gap — a
            // total absence of *any* approved conversion for their real
            // capacity type: distance for Handstand Walk, a climb count
            // for Rope Climb, load/%1RM for Clean/Jerk/Snatch). This
            // exclusion is PURPOSE-SPECIFIC (only `.conditioning`, this
            // type's only real purpose today) and UNCONDITIONAL on
            // proficiency — "regardless of proficiency" per the order's
            // own text, so it applies even when no `proficiency` lookup
            // is supplied (unlike the rep-tracked check below, which only
            // engages once real capability tracking is wired in). It does
            // NOT touch these exercises' Skill/Power/Strength/source-
            // authored usage — none of those paths call this selector at
            // all (`materializeStrengthBlock`'s own separate
            // `SubstituteExerciseUseCase`/`ResolveProgramInstanceExerciseSlotsUseCase`
            // path is untouched by this checkpoint), so the exclusion is
            // structurally confined to conditioning composition already,
            // not merely by this `purpose` check.
            if input.purpose == .conditioning, TechnicalCapacityDoseAuthority.conditioningExcludedNames.contains(exercise.canonicalName) {
                return false
            }
            // CONDITIONING DOSE AUTHORITY V1, Sections 10-13: real
            // per-athlete capability/capacity gating for the 7 rep-based
            // gated technical movements now applies for CONDITIONING
            // purpose independent of `Exercise.requiresDemonstratedCapability`
            // — a narrower, pre-existing catalog flag some of these 7
            // (Double-Unders/Pull-up/Toes-to-Bar) were never given (CP1's
            // own "auto-eligible day one" default, preserved for every
            // OTHER purpose/gating question). Only engages when BOTH a
            // real `proficiency` lookup is supplied AND purpose is
            // `.conditioning` — nil `proficiency` (every pre-existing
            // call site/test) is completely unaffected.
            if input.purpose == .conditioning, let proficiencyLookup = input.proficiency {
                if TechnicalCapacityDoseAuthority.repeatedDoseTrackedNames.contains(exercise.canonicalName) {
                    switch proficiencyLookup(exercise) {
                    case .learning:
                        // Section 10: LEARNING never a conditioning
                        // dependency — applies even to the 3 of these 7
                        // names CP1 left globally un-flagged (Double-
                        // Unders/Pull-up/Toes-to-Bar's own "auto-eligible
                        // by default" precedent), once an athlete has an
                        // EXPLICIT recorded LEARNING state for that
                        // specific movement.
                        return false
                    case .workoutReady:
                        guard let capacity = input.capacity?(exercise),
                              capacity.type == .maxUnbrokenReps || capacity.type == .maxReps,
                              TechnicalCapacityDoseAuthority.maxRepeatedDose(forCapacity: capacity.value) != nil
                        else { return false } // Section 12: no usable capacity evidence.
                    case .unknown:
                        // Preserve CP1's own established default exactly:
                        // Double-Unders/Pull-up/Toes-to-Bar remain
                        // auto-eligible when nothing is explicitly
                        // recorded for this athlete; the other 4 tracked
                        // names here are already globally gated via
                        // `Exercise.requiresDemonstratedCapability` and
                        // are handled, unchanged, by the existing check
                        // below.
                        break
                    }
                }
            }
            guard exercise.requiresDemonstratedCapability else { return true }
            guard let proficiencyLookup = input.proficiency else { return false }
            switch (input.purpose, proficiencyLookup(exercise)) {
            case (.conditioning, .workoutReady): return true
            case (.skillPractice, .learning), (.skillPractice, .workoutReady): return true
            default: return false
            }
        }
        let ordinaryEligible = eligible.filter(isCapabilityEligible)
        if let picked = ordinaryEligible.min(by: leastExposedFirst) {
            return .resolved(picked)
        } else if let advancedOnly = eligible.min(by: leastExposedFirst) {
            return .capabilityUnknown(advancedOnly)
        } else {
            return .none
        }
    }
}
