import Foundation
import SwiftData

/// Builds the approved Hypertrophy sequencing — Basic Hypertrophy ->
/// Metabolite Focus -> Resensitization — as 3 independent
/// `ProgramDefinition`/`TrainingPhase`/`ProgramInstance` triples attached,
/// in order, to one `TrainingPlan`. **No new "ProgramJourney" entity
/// exists** — `TrainingPlan.orderedPhases` (pre-existing since Stage 1)
/// already provides the sequencing; see `TrainingPhase.swift`'s
/// "ProgramJourney note" and Stage 3 decision A1. This type only
/// automates *building* that shape for Hypertrophy specifically.
///
/// Each phase remains independently startable: this function creates all
/// 3 phases' `ProgramDefinition`/`TrainingPhase`/`ProgramInstance` up
/// front (so the whole journey is inspectable/previewable before any of
/// it runs), but does **not** materialize any phase's actual Sessions —
/// that's `StrengthMaterializer`'s job, called per-phase whenever that
/// phase actually starts, with that phase's own starting RM (from
/// `PerformanceProfile` if history exists, calibration otherwise — never
/// a cross-phase spreadsheet formula, per decision A1).
enum HypertrophyProgramJourney {
    static let orderedPhaseTypes: [HypertrophyPhaseType] = [.basicHypertrophy, .metaboliteFocus, .resensitization]

    struct PhaseResult {
        var phaseType: HypertrophyPhaseType
        var phase: TrainingPhase
        var definition: ProgramDefinition
        var instance: ProgramInstance
    }

    /// `phaseLengthWeeks` spaces each phase's `startDate` sequentially
    /// (5 weeks — 4 progressive + 1 deload — matches
    /// `HypertrophyProgramGenerator`'s own `lengthWeeks`); a caller
    /// starting phases as they're actually reached rather than all at
    /// once may simply ignore the computed `startDate`s past the first.
    @discardableResult
    static func build(
        dayCount: Int,
        split: HypertrophySplit,
        plan: TrainingPlan,
        ownerUserID: UUID,
        firstPhaseStartDate: Date,
        phaseLengthWeeks: Int = 5,
        context: ModelContext
    ) throws -> [PhaseResult] {
        var results: [PhaseResult] = []
        var phaseStartDate = firstPhaseStartDate

        for phaseType in orderedPhaseTypes {
            let definition = try HypertrophyProgramGenerator.generate(
                configuration: HypertrophyProgramConfiguration(dayCount: dayCount, split: split, phaseType: phaseType),
                provenance: .constructed(reason: "Generated by HypertrophyProgramGenerator; no source workbook exists in this repository."),
                context: context
            )

            let phase = TrainingPhase(type: .muscleGain, startDate: phaseStartDate, priorityRule: .strength, status: .planned)
            context.insert(phase)
            plan.addPhase(phase)

            let instance = ProgramInstance(ownerUserID: ownerUserID, startDate: phaseStartDate, status: .planned)
            context.insert(instance)
            instance.programDefinition = definition
            phase.addProgramInstance(instance)

            results.append(PhaseResult(phaseType: phaseType, phase: phase, definition: definition, instance: instance))

            guard let nextStart = Calendar.current.date(byAdding: .weekOfYear, value: phaseLengthWeeks, to: phaseStartDate) else { break }
            phaseStartDate = nextStart
        }

        return results
    }
}
